### ISSUE TITLE
false statement

### ISSUE THREAD

**Issue by GottZ** [james-fray/YouTube-HD#10]
this post is removed since it contains links to untrusted websites. You should always refer to the source code from either AMO, Opera add-ons, or Google's official website.

**Comment by james-fray** [comment]
there is no jQuery in the code!

**Comment by james-fray** [comment]
The extension got removed based on a report that it is not functioning

**Comment by james-fray** [comment]
btw, my lastest version is 0.2.5; https://addons.mozilla.org/en-US/firefox/addon/youtube-hd-1/

**Comment by james-fray** [comment]
You must have mixed this extension with another one. Mine is open-source and the full code is available on GitHub and AMO website. Don't spam around ;)
