### ISSUE TITLE
Not working Safari 8.0.6

### ISSUE THREAD

**Issue by bloodstrike** [james-fray/YouTube-HD#3]
Installed YouTube-HD in Safari 8.0.6 (10600.6.3) and the following error appears in the console when a video loads:

[Error] SyntaxError: Unexpected end of script
    (anonymous function) (data:text/javascript,var iyhListenerChange = (function (quality, hd) {    return function iyhListenerChange (e) {      if (e === 1) {        var player = document.getElementById('movie_player') || document.getElementById('movie_player-flash');        var levels = player.getAvailableQualityLevels();        var q = player.getPlaybackQuality();        if (q.indexOf('hd') !== -1 && hd) {          //console.error('YouTube HD::', 'Quality was', q, 'Changing quality is skipped');          return;        }        var tmp = quality === '-1' || levels.indexOf(quality) === -1 ?%20levels[0]%20:%20quality;%20%20%20%20%20%20%20%20player.setPlaybackQuality(tmp);%20%20%20%20%20%20%20%20//console.error('YouTube%20HD::',%20'Quality%20was',%20q,%20'Quality%20is%20set%20to',%20tmp);%20%20%20%20%20%20}%20%20%20%20};%20%20})(%22hd1080%22,false);(function%20inject()%20{%20%20%20%20function%20one%20()%20{%20%20%20%20%20%20var%20player%20=%20document.getElementById('movie_player')%20||%20document.getElementById('movie_player-flash');%20%20%20%20%20%20if%20(player%20&&%20player.addEventListener%20&&%20player.getPlayerState)%20{%20%20%20%20%20%20%20%20player.addEventListener('onStateChange',%20'iyhListenerChange');%20%20%20%20%20%20%20%20iyhListenerChange(1);%20%20%20%20%20%20}%20%20%20%20%20%20else%20{%20%20%20%20%20%20%20%20window.setTimeout(one,%201000);%20%20%20%20%20%20}%20%20%20%20}%20%20%20%20one();%20%20})();, line 1)

Inspecting the source of the script in question using Safari's developer tools, everything past the first comment line (//console.error...) is marked as a comment, probably due to all the white space from that point on being encoded into HTML entities.

**Comment by james-fray** [comment]
Is this fixed?

**Comment by bloodstrike** [comment]
Reinstalled and extension is successfully choosing the highest quality. There are still errors showing up in the console, but it's working, so that's all I need! Thanks!
