### ISSUE TITLE
Doesn't work on safari

### ISSUE THREAD

**Issue by joemerlino** [james-fray/YouTube-HD#4]
Hi, thanks for your update with the toolbar button, but if I set the quality on 720p and then go to youtube it still loads the video using the autoresolution. Can you fix this bug? thanks in advance :)

**Comment by james-fray** [comment]
Even if you refresh the video page? You mean the extension is not working anymore?

**Comment by joemerlino** [comment]
Doesn't work :( if i choose 720p should set that quality right? instead the video still loads with autoresolution even refreshing the video page doesn't change it.

**Comment by james-fray** [comment]
It works just fine for me. If you select 720p in the settings, the extension will try to keep the quality at 720p unless you manually change the quality.

To find out what is going on, open YouTube page, right click somewhere and select `inspect element` now click on the console tab. You should get some messages like this:

![screen shot 2015-06-27 at 14 28 01](https://cloud.githubusercontent.com/assets/9897733/8391450/69d7acb2-1cd9-11e5-9240-721977af630d.png)

**Comment by joemerlino** [comment]
I get this: 
![schermata 2015-06-28 alle 13 26 09](https://cloud.githubusercontent.com/assets/7900234/8396140/59cdc9ee-1d99-11e5-87f1-8f5b90678cf1.png)

**Comment by james-fray** [comment]
> instead the video still loads with autoresolution even refreshing the video page doesn't change it.

So the extension checks the current player quality and if it matches to what you have already set in the settings page, no change is applied. As you can see in the log window, no action is taken place. However, if you change the quality to 480p for instance, the extension will change it back to 720p.
