### ISSUE TITLE
Embedded videos?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [james-fray/YouTube-HD#5]
Seems to work on YT, but not embedded YT vids? That's a shame because I hardly ever actually go to YT, but I watch lots of embedded vids using [YTOHP](http://add0n.com/youtube-hover.html). Really wish it worked everywhere.

**Comment by james-fray** [comment]
Well, we never had a use case for embedded players so the script was limited to the matching top frames (youtube.com for instance). I changed the script injection to allow sub frames. This should work, however, I haven't yet tried it with @schomery's YTOHP.

You can try the dev version here: https://github.com/james-fray/YouTube-HD/tree/master/src. Turn on the log from options page to make sure the add-on is actually working.

**Comment by narcolepticinsomniac** [comment]
Just tested briefly, and it certainly seems like you nailed it. Works with all embedded videos tested so far. I appreciate the quick response and fix. Really handy extension now.
