### ISSUE TITLE
Add option for non forced quality

### ISSUE THREAD

**Issue by ghost** [james-fray/YouTube-HD#8]
Currently the quality setting is forced. I would rather prefer an additional option without forcing the quality settings.

Example:
Set the preferred HD quality to 'large' (480p) for reduced bandwith. An whenever I would like to see a video in actual HD quality (eg. 720p or 1080p) I can still change the web player settings accordingly.
Right now if I change the quality to 720p it is set back to 480p in the matter of seconds.

By not using the auto quality settings it should generally stay at whatever quality is selected. (I am not signed in to google, so I cant change my quality settings there)

**Comment by james-fray** [comment]
> Right now if I change the quality to 720p it is set back to 480p in the matter of seconds.

If you set the default value to an HD, the extension is not going to alter it. But when you set to a not-hd quality it is forced.

We can have two new options:
1. Only force the quality once
2. Do not force quality when the current quality is higher than the defined one.

**Comment by ghost** [comment]
perfect 👍 thanks.
I just noticed the current version is at 0.2.4, whereas the Safari version is still at 0.2.2.
Would be nice to actually use the fix :D

**Comment by james-fray** [comment]
> whereas the Safari version is still at 0.2.2.

Ah, I didn't know that you are using Safari. Sorry, but the Safari store requests 100$ per year to keep the account active for developments so I decided to drop the Safari development!
